-- V1 now creates Course_CO/Course_PO with composite primary keys directly.
-- This migration is kept for historical tracking but performs no schema changes.
-- Previous versions of this migration attempted to add keys here, but that is now
-- handled in V1 to ensure clean deployments.
