-- Thresholds' PRIMARY KEY (type) is now declared directly in V1's CREATE TABLE
-- statement, so it's applied for all fresh installations. This migration is kept for
-- historical tracking but is a no-op since V1 already handles the primary key definition.
