spring:
  application:
    name: co-po-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/co_po?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sinhawiz}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:1fc051ff98d769ef846ab7905a14740d39dc0d8f8e8aab9f088cd1541c232eee}
  expiration: 86400000 # 1 day in ms
  
server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
